const productSeeds = [
  {id: 1, name: "Eachine E58 2MP 720P Camera WIFI FPV Foldable Drone 2.4G 6-Axis RC Quadcopter", condition: "New", minimum: 10, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 2, name: "EVGA Graphics Card", condition: "New", minimum: 20, watchers: 4, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 3, name: "Massager", condition: "New", minimum: 12, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 4, name: "Cookware", condition: "New", minimum: 20, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 5, name: "Treadmill Sheets", condition: "New", minimum: 40, watchers: 6, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 6, name: "Apple Mouse", condition: "New", minimum: 10, watchers: 2, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 7, name: "iPhone 6", condition: "New", minimum: 20, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 8, name: "iPhone 7", condition: "New", minimum: 30, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 9, name: "iPhone X", condition: "New", minimum: 40, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 10, name: "Whiteboards", condition: "New", minimum: 50, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 11, name: "Pens", condition: "New", minimum: 10, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 12, name: "North Face Backpack", condition: "New", minimum: 10, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 13, name: "Apple Earbuds", condition: "New", minimum: 40, watchers: 2, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 14, name: "Expo Markers", condition: "New", minimum: 40, watchers: 2, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 15, name: "Hand-Crafted Desk", condition: "New", minimum: 40, watchers: 4, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 16, name: "Recliner", condition: "New", minimum: 40, watchers: 6, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 17, name: "Large Umbrella", condition: "New", minimum: 50, watchers: 1, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 18, name: "Macbook Pro", condition: "New", minimum: 50, watchers: 1, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 19, name: "Macbook Air", condition: "New", minimum: 50, watchers: 1, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 20, name: "Tires", condition: "New", minimum: 50, watchers: 1, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 21, name: "2011 Honda Accord", condition: "New", minimum: 50, watchers: 1, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 22, name: "Black Sweater", condition: "New", minimum: 50, watchers: 1, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 23, name: "HydroFlask", condition: "New", minimum: 20, watchers: 1, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 24, name: "Pack of 5 Peanuts", condition: "New", minimum: 20, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 25, name: "Jean Jacket", condition: "New", minimum: 20, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 26, name: "Apple Earbud Convertew", condition: "New", minimum: 30, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 27, name: "Gmail Account", condition: "New", minimum: 40, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 28, name: "Drone", condition: "New", minimum: 20, watchers: 9, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 29, name: "Box of Pizza", condition: "New", minimum: 5, watchers: 9, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 30, name: "Apple Macbook Charger", condition: "New", minimum: 15, watchers: 9, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 31, name: "HP Spectre Laptop", condition: "New", minimum: 13, watchers: 7, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 32, name: "Juice", condition: "New", minimum: 15, watchers: 7, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 33, name: "Prescription Glasses", condition: "New", minimum: 60, watchers: 6, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 34, name: "Baseball Cap", condition: "New", minimum: 60, watchers: 5, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 35, name: "Dog Toys and Treats", condition: "New", minimum: 23, watchers: 4, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 36, name: "Amazon Key Home Kit", condition: "New", minimum: 53, watchers: 2, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 37, name: "Kitchen Sink Strainer", condition: "New", minimum: 56, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 38, name: "Echo Dot", condition: "New", minimum: 34, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 39, name: "Bike Seat Cover", condition: "New", minimum: 20, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 40, name: "Magnetic Phone Car Mount", condition: "New", minimum: 20, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 41, name: "iPhone Cable", condition: "New", minimum: 20, watchers: 1, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 42, name: "Rankie Micro USB", condition: "Like New", minimum: 20, watchers: 1, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 43, name: "Dishwasher Detergent", condition: "Like New", minimum: 20, watchers: 1, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 44, name: "High Potency Biotin", condition: "Like New", minimum: 20, watchers: 1, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 45, name: "Fiji Water", condition: "Like New", minimum: 20, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 46, name: "50ft Garden Hose", condition: "Like New", minimum: 20, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 47, name: "Lightning Cable Charger", condition: "Like New", minimum: 20, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 48, name: "Bluetooth Headphones", condition: "Like New", minimum: 20, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 49, name: "Amazon Tap", condition: "Like New", minimum: 40, watchers: 4, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 50, name: "Meat Thermometer", condition: "Like New", minimum: 40, watchers: 4, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 51, name: "Cell Phone Stand", condition: "Like New", minimum: 40, watchers: 4, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 52, name: "Echo Spot", condition: "Like New", minimum: 40, watchers: 4, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 53, name: "Power Strip Tower", condition: "Like New", minimum: 40, watchers: 2, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 54, name: "Power Strip", condition: "Like New", minimum: 40, watchers: 2, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 55, name: "Mens Shoes", condition: "Like New", minimum: 40, watchers: 2, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 56, name: "LaserGrip", condition: "Like New", minimum: 40, watchers: 2, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 57, name: "Lavender Oil", condition: "Like New", minimum: 10, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 58, name: "Colgate Dash Button", condition: "Like New", minimum: 10, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 59, name: "Skiing Lesson", condition: "Like New", minimum: 10, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 60, name: "Karate Lesson", condition: "Like New", minimum: 10, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 61, name: "Piano Lesson", condition: "Like New", minimum: 10, watchers: 1, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 62, name: "Guitar Lesson", condition: "Like New", minimum: 10, watchers: 1, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 63, name: "Brush Pens", condition: "Good", minimum: 30, watchers: 1, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 64, name: "Kindle", condition: "Good", minimum: 50, watchers: 1, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 65, name: "Running Belt", condition: "Good", minimum: 10, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 66, name: "Running Shoes", condition: "Good", minimum: 10, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 67, name: "Plants", condition: "Good", minimum: 10, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 68, name: "Office Space", condition: "Good", minimum: 10, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 69, name: "Shopping Bag", condition: "Good", minimum: 10, watchers: 4, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 70, name: "Cardboard", condition: "Good", minimum: 10, watchers: 4, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 71, name: "Vitamins", condition: "Good", minimum: 10, watchers: 4, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 72, name: "Dirt Bike", condition: "Good", minimum: 10, watchers: 4, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 73, name: "Dirt", condition: "Good", minimum: 10, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 74, name: "License Plate", condition: "Good", minimum: 10, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 75, name: "Stop Sign", condition: "Good", minimum: 10, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 76, name: "Vintage Baseball Cards", condition: "Good", minimum: 10, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 77, name: "Magic the Gathering Cards", condition: "Good", minimum: 10, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 78, name: "Sony TV", condition: "Good", minimum: 10, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 79, name: "4k Monitor", condition: "Good", minimum: 11, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 80, name: "Trip to the Zoo", condition: "Good", minimum: 11, watchers: 0, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 81, name: "DisneyLand Tickets", condition: "Good", minimum: 20, watchers: 2, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 82, name: "Photo of Me", condition: "Good", minimum: 20, watchers: 2, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 83, name: "Photo of You", condition: "Good", minimum: 20, watchers: 2, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 84, name: "Wedding DJ", condition: "Good", minimum: 20, watchers: 2, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 85, name: "Door", condition: "Good", minimum: 20, watchers: 5, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 86, name: "Figurines", condition: "Good", minimum: 20, watchers: 5, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 87, name: "New Skates", condition: "Poor", minimum: 10, watchers: 5, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 88, name: "Black Suit", condition: "Poor", minimum: 20, watchers: 5, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 89, name: "Boots", condition: "Poor", minimum: 30, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 90, name: "Canteen", condition: "Poor", minimum: 30, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 91, name: "LOTR DVD Set", condition: "Poor", minimum: 30, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 92, name: "A Real Product", condition: "Poor", minimum: 30, watchers: 3, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 93, name: "PS4", condition: "Poor", minimum: 30, watchers: 4, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 94, name: "DualShock Controller", condition: "Poor", minimum: 30, watchers: 4, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 95, name: "Video Games", condition: "Poor", minimum: 30, watchers: 4, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 96, name: "YouTube Account", condition: "Poor", minimum: 30, watchers: 4, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 97, name: "One Rib", condition: "Poor", minimum: 50, watchers: 5, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 98, name: "iPhone Case", condition: "Poor", minimum: 10, watchers: 5, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 99, name: "Trash", condition: "Poor", minimum: 15, watchers: 5, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()},
  {id: 100, name: "Trash Can", condition: "Poor", minimum: 16, watchers: 5, endtime: new Date(), createdAt: new Date(), updatedAt: new Date()}
];

const bidSeeds = [
  {productId: 1, amount: 140, createdAt: new Date(), updatedAt: new Date()},
  {productId: 2, amount: 140, createdAt: new Date(), updatedAt: new Date()},
  {productId: 3, amount: 140, createdAt: new Date(), updatedAt: new Date()},
  {productId: 4, amount: 140, createdAt: new Date(), updatedAt: new Date()},
  {productId: 5, amount: 140, createdAt: new Date(), updatedAt: new Date()},
  {productId: 6, amount: 140, createdAt: new Date(), updatedAt: new Date()},
  {productId: 7, amount: 140, createdAt: new Date(), updatedAt: new Date()},
  {productId: 8, amount: 140, createdAt: new Date(), updatedAt: new Date()},
  {productId: 9, amount: 140, createdAt: new Date(), updatedAt: new Date()},
  {productId: 10, amount: 310, createdAt: new Date(), updatedAt: new Date()},
  {productId: 11, amount: 310, createdAt: new Date(), updatedAt: new Date()},
  {productId: 12, amount: 310, createdAt: new Date(), updatedAt: new Date()},
  {productId: 13, amount: 310, createdAt: new Date(), updatedAt: new Date()},
  {productId: 14, amount: 310, createdAt: new Date(), updatedAt: new Date()},
  {productId: 15, amount: 310, createdAt: new Date(), updatedAt: new Date()},
  {productId: 16, amount: 310, createdAt: new Date(), updatedAt: new Date()},
  {productId: 17, amount: 310, createdAt: new Date(), updatedAt: new Date()},
  {productId: 18, amount: 310, createdAt: new Date(), updatedAt: new Date()},
  {productId: 19, amount: 310, createdAt: new Date(), updatedAt: new Date()},
  {productId: 20, amount: 310, createdAt: new Date(), updatedAt: new Date()},
  {productId: 21, amount: 160, createdAt: new Date(), updatedAt: new Date()},
  {productId: 22, amount: 160, createdAt: new Date(), updatedAt: new Date()},
  {productId: 23, amount: 160, createdAt: new Date(), updatedAt: new Date()},
  {productId: 24, amount: 160, createdAt: new Date(), updatedAt: new Date()},
  {productId: 25, amount: 160, createdAt: new Date(), updatedAt: new Date()},
  {productId: 26, amount: 160, createdAt: new Date(), updatedAt: new Date()},
  {productId: 27, amount: 160, createdAt: new Date(), updatedAt: new Date()},
  {productId: 28, amount: 160, createdAt: new Date(), updatedAt: new Date()},
  {productId: 29, amount: 160, createdAt: new Date(), updatedAt: new Date()},
  {productId: 30, amount: 160, createdAt: new Date(), updatedAt: new Date()},
  {productId: 31, amount: 160, createdAt: new Date(), updatedAt: new Date()},
  {productId: 32, amount: 130, createdAt: new Date(), updatedAt: new Date()},
  {productId: 33, amount: 130, createdAt: new Date(), updatedAt: new Date()},
  {productId: 34, amount: 130, createdAt: new Date(), updatedAt: new Date()},
  {productId: 35, amount: 130, createdAt: new Date(), updatedAt: new Date()},
  {productId: 36, amount: 130, createdAt: new Date(), updatedAt: new Date()},
  {productId: 37, amount: 130, createdAt: new Date(), updatedAt: new Date()},
  {productId: 38, amount: 130, createdAt: new Date(), updatedAt: new Date()},
  {productId: 39, amount: 130, createdAt: new Date(), updatedAt: new Date()},
  {productId: 40, amount: 130, createdAt: new Date(), updatedAt: new Date()},
  {productId: 41, amount: 130, createdAt: new Date(), updatedAt: new Date()},
  {productId: 42, amount: 130, createdAt: new Date(), updatedAt: new Date()},
  {productId: 43, amount: 800, createdAt: new Date(), updatedAt: new Date()},
  {productId: 44, amount: 800, createdAt: new Date(), updatedAt: new Date()},
  {productId: 45, amount: 800, createdAt: new Date(), updatedAt: new Date()},
  {productId: 46, amount: 800, createdAt: new Date(), updatedAt: new Date()},
  {productId: 47, amount: 800, createdAt: new Date(), updatedAt: new Date()},
  {productId: 48, amount: 800, createdAt: new Date(), updatedAt: new Date()},
  {productId: 49, amount: 800, createdAt: new Date(), updatedAt: new Date()},
  {productId: 50, amount: 800, createdAt: new Date(), updatedAt: new Date()},
  {productId: 51, amount: 800, createdAt: new Date(), updatedAt: new Date()},
  {productId: 52, amount: 800, createdAt: new Date(), updatedAt: new Date()},
  {productId: 53, amount: 800, createdAt: new Date(), updatedAt: new Date()},
  {productId: 54, amount: 320, createdAt: new Date(), updatedAt: new Date()},
  {productId: 55, amount: 320, createdAt: new Date(), updatedAt: new Date()},
  {productId: 56, amount: 320, createdAt: new Date(), updatedAt: new Date()},
  {productId: 57, amount: 320, createdAt: new Date(), updatedAt: new Date()},
  {productId: 58, amount: 320, createdAt: new Date(), updatedAt: new Date()},
  {productId: 59, amount: 320, createdAt: new Date(), updatedAt: new Date()},
  {productId: 60, amount: 320, createdAt: new Date(), updatedAt: new Date()},
  {productId: 61, amount: 320, createdAt: new Date(), updatedAt: new Date()},
  {productId: 62, amount: 320, createdAt: new Date(), updatedAt: new Date()},
  {productId: 63, amount: 320, createdAt: new Date(), updatedAt: new Date()},
  {productId: 64, amount: 320, createdAt: new Date(), updatedAt: new Date()},
  {productId: 65, amount: 812, createdAt: new Date(), updatedAt: new Date()},
  {productId: 66, amount: 812, createdAt: new Date(), updatedAt: new Date()},
  {productId: 67, amount: 812, createdAt: new Date(), updatedAt: new Date()},
  {productId: 68, amount: 812, createdAt: new Date(), updatedAt: new Date()},
  {productId: 69, amount: 812, createdAt: new Date(), updatedAt: new Date()},
  {productId: 70, amount: 812, createdAt: new Date(), updatedAt: new Date()},
  {productId: 71, amount: 812, createdAt: new Date(), updatedAt: new Date()},
  {productId: 72, amount: 812, createdAt: new Date(), updatedAt: new Date()},
  {productId: 73, amount: 812, createdAt: new Date(), updatedAt: new Date()},
  {productId: 74, amount: 812, createdAt: new Date(), updatedAt: new Date()},
  {productId: 75, amount: 812, createdAt: new Date(), updatedAt: new Date()},
  {productId: 76, amount: 210, createdAt: new Date(), updatedAt: new Date()},
  {productId: 77, amount: 210, createdAt: new Date(), updatedAt: new Date()},
  {productId: 78, amount: 210, createdAt: new Date(), updatedAt: new Date()},
  {productId: 79, amount: 210, createdAt: new Date(), updatedAt: new Date()},
  {productId: 80, amount: 210, createdAt: new Date(), updatedAt: new Date()},
  {productId: 81, amount: 210, createdAt: new Date(), updatedAt: new Date()},
  {productId: 82, amount: 210, createdAt: new Date(), updatedAt: new Date()},
  {productId: 83, amount: 210, createdAt: new Date(), updatedAt: new Date()},
  {productId: 84, amount: 210, createdAt: new Date(), updatedAt: new Date()},
  {productId: 85, amount: 210, createdAt: new Date(), updatedAt: new Date()},
  {productId: 86, amount: 210, createdAt: new Date(), updatedAt: new Date()},
  {productId: 87, amount: 123, createdAt: new Date(), updatedAt: new Date()},
  {productId: 88, amount: 123, createdAt: new Date(), updatedAt: new Date()},
  {productId: 89, amount: 123, createdAt: new Date(), updatedAt: new Date()},
  {productId: 90, amount: 123, createdAt: new Date(), updatedAt: new Date()},
  {productId: 91, amount: 123, createdAt: new Date(), updatedAt: new Date()},
  {productId: 92, amount: 123, createdAt: new Date(), updatedAt: new Date()},
  {productId: 93, amount: 123, createdAt: new Date(), updatedAt: new Date()},
  {productId: 94, amount: 123, createdAt: new Date(), updatedAt: new Date()},
  {productId: 95, amount: 123, createdAt: new Date(), updatedAt: new Date()},
  {productId: 96, amount: 123, createdAt: new Date(), updatedAt: new Date()},
  {productId: 97, amount: 123, createdAt: new Date(), updatedAt: new Date()},
  {productId: 98, amount: 123, createdAt: new Date(), updatedAt: new Date()},
  {productId: 99, amount: 345, createdAt: new Date(), updatedAt: new Date()},
  {productId: 100, amount: 123, createdAt: new Date(), updatedAt: new Date()}
];

module.exports = {
  productSeeds: productSeeds,
  bidSeeds: bidSeeds
};