const productSeeds = [
  {name: "Eachine E58 2MP 720P Camera WIFI FPV Foldable Drone 2.4G 6-Axis RC Quadcopter", condition: "New", minimum: 10, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "EVGA Graphics Card", condition: "New", minimum: 20, watchers: 4, endtime: CURRENT_TIMESTAMP},
  {name: "Massager", condition: "New", minimum: 12, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "Cookware", condition: "New", minimum: 20, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Treadmill Sheets", condition: "New", minimum: 40, watchers: 6, endtime: CURRENT_TIMESTAMP},
  {name: "Apple Mouse", condition: "New", minimum: 10, watchers: 2, endtime: CURRENT_TIMESTAMP},
  {name: "iPhone 6", condition: "New", minimum: 20, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "iPhone 7", condition: "New", minimum: 30, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "iPhone X", condition: "New", minimum: 40, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "Whiteboards", condition: "New", minimum: 50, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "Pens", condition: "New", minimum: 10, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "North Face Backpack", condition: "New", minimum: 10, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Apple Earbuds", condition: "New", minimum: 40, watchers: 2, endtime: CURRENT_TIMESTAMP},
  {name: "Expo Markers", condition: "New", minimum: 40, watchers: 2, endtime: CURRENT_TIMESTAMP},
  {name: "Hand-Crafted Desk", condition: "New", minimum: 40, watchers: 4, endtime: CURRENT_TIMESTAMP},
  {name: "Recliner", condition: "New", minimum: 40, watchers: 6, endtime: CURRENT_TIMESTAMP},
  {name: "Large Umbrella", condition: "New", minimum: 50, watchers: 1, endtime: CURRENT_TIMESTAMP},
  {name: "Macbook Pro", condition: "New", minimum: 50, watchers: 1, endtime: CURRENT_TIMESTAMP},
  {name: "Macbook Air", condition: "New", minimum: 50, watchers: 1, endtime: CURRENT_TIMESTAMP},
  {name: "Tires", condition: "New", minimum: 50, watchers: 1, endtime: CURRENT_TIMESTAMP},
  {name: "2011 Honda Accord", condition: "New", minimum: 50, watchers: 1, endtime: CURRENT_TIMESTAMP},
  {name: "Black Sweater", condition: "New", minimum: 50, watchers: 1, endtime: CURRENT_TIMESTAMP},
  {name: "HydroFlask", condition: "New", minimum: 20, watchers: 1, endtime: CURRENT_TIMESTAMP},
  {name: "Pack of 5 Peanuts", condition: "New", minimum: 20, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "Jean Jacket", condition: "New", minimum: 20, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "Apple Earbud Convertew", condition: "New", minimum: 30, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "Gmail Account", condition: "New", minimum: 40, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "Drone", condition: "New", minimum: 20, watchers: 9, endtime: CURRENT_TIMESTAMP},
  {name: "Box of Pizza", condition: "New", minimum: 5, watchers: 9, endtime: CURRENT_TIMESTAMP},
  {name: "Apple Macbook Charger", condition: "New", minimum: 15, watchers: 9, endtime: CURRENT_TIMESTAMP},
  {name: "HP Spectre Laptop", condition: "New", minimum: 13, watchers: 7, endtime: CURRENT_TIMESTAMP},
  {name: "Juice", condition: "New", minimum: 15, watchers: 7, endtime: CURRENT_TIMESTAMP},
  {name: "Prescription Glasses", condition: "New", minimum: 60, watchers: 6, endtime: CURRENT_TIMESTAMP},
  {name: "Baseball Cap", condition: "New", minimum: 60, watchers: 5, endtime: CURRENT_TIMESTAMP},
  {name: "Dog Toys and Treats", condition: "New", minimum: 23, watchers: 4, endtime: CURRENT_TIMESTAMP},
  {name: "Amazon Key Home Kit", condition: "New", minimum: 53, watchers: 2, endtime: CURRENT_TIMESTAMP},
  {name: "Kitchen Sink Strainer", condition: "New", minimum: 56, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Echo Dot", condition: "New", minimum: 34, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Bike Seat Cover", condition: "New", minimum: 20, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Magnetic Phone Car Mount", condition: "New", minimum: 20, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "iPhone Cable", condition: "New", minimum: 20, watchers: 1, endtime: CURRENT_TIMESTAMP},
  {name: "Rankie Micro USB", condition: "Like New", minimum: 20, watchers: 1, endtime: CURRENT_TIMESTAMP},
  {name: "Dishwasher Detergent", condition: "Like New", minimum: 20, watchers: 1, endtime: CURRENT_TIMESTAMP},
  {name: "High Potency Biotin", condition: "Like New", minimum: 20, watchers: 1, endtime: CURRENT_TIMESTAMP},
  {name: "Fiji Water", condition: "Like New", minimum: 20, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "50ft Garden Hose", condition: "Like New", minimum: 20, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Lightning Cable Charger", condition: "Like New", minimum: 20, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Bluetooth Headphones", condition: "Like New", minimum: 20, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Amazon Tap", condition: "Like New", minimum: 40, watchers: 4, endtime: CURRENT_TIMESTAMP},
  {name: "Meat Thermometer", condition: "Like New", minimum: 40, watchers: 4, endtime: CURRENT_TIMESTAMP},
  {name: "Cell Phone Stand", condition: "Like New", minimum: 40, watchers: 4, endtime: CURRENT_TIMESTAMP},
  {name: "Echo Spot", condition: "Like New", minimum: 40, watchers: 4, endtime: CURRENT_TIMESTAMP},
  {name: "Power Strip Tower", condition: "Like New", minimum: 40, watchers: 2, endtime: CURRENT_TIMESTAMP},
  {name: "Power Strip", condition: "Like New", minimum: 40, watchers: 2, endtime: CURRENT_TIMESTAMP},
  {name: "Mens Shoes", condition: "Like New", minimum: 40, watchers: 2, endtime: CURRENT_TIMESTAMP},
  {name: "LaserGrip", condition: "Like New", minimum: 40, watchers: 2, endtime: CURRENT_TIMESTAMP},
  {name: "Lavender Oil", condition: "Like New", minimum: 10, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Colgate Dash Button", condition: "Like New", minimum: 10, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Skiing Lesson", condition: "Like New", minimum: 10, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Karate Lesson", condition: "Like New", minimum: 10, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Piano Lesson", condition: "Like New", minimum: 10, watchers: 1, endtime: CURRENT_TIMESTAMP},
  {name: "Guitar Lesson", condition: "Like New", minimum: 10, watchers: 1, endtime: CURRENT_TIMESTAMP},
  {name: "Brush Pens", condition: "Good", minimum: 30, watchers: 1, endtime: CURRENT_TIMESTAMP},
  {name: "Kindle", condition: "Good", minimum: 50, watchers: 1, endtime: CURRENT_TIMESTAMP},
  {name: "Running Belt", condition: "Good", minimum: 10, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "Running Shoes", condition: "Good", minimum: 10, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "Plants", condition: "Good", minimum: 10, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "Office Space", condition: "Good", minimum: 10, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "Shopping Bag", condition: "Good", minimum: 10, watchers: 4, endtime: CURRENT_TIMESTAMP},
  {name: "Cardboard", condition: "Good", minimum: 10, watchers: 4, endtime: CURRENT_TIMESTAMP},
  {name: "Vitamins", condition: "Good", minimum: 10, watchers: 4, endtime: CURRENT_TIMESTAMP},
  {name: "Dirt Bike", condition: "Good", minimum: 10, watchers: 4, endtime: CURRENT_TIMESTAMP},
  {name: "Dirt", condition: "Good", minimum: 10, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "License Plate", condition: "Good", minimum: 10, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Stop Sign", condition: "Good", minimum: 10, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Vintage Baseball Cards", condition: "Good", minimum: 10, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Magic the Gathering Cards", condition: "Good", minimum: 10, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "Sony TV", condition: "Good", minimum: 10, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "4k Monitor", condition: "Good", minimum: 11, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "Trip to the Zoo", condition: "Good", minimum: 11, watchers: 0, endtime: CURRENT_TIMESTAMP},
  {name: "DisneyLand Tickets", condition: "Good", minimum: 20, watchers: 2, endtime: CURRENT_TIMESTAMP},
  {name: "Photo of Me", condition: "Good", minimum: 20, watchers: 2, endtime: CURRENT_TIMESTAMP},
  {name: "Photo of You", condition: "Good", minimum: 20, watchers: 2, endtime: CURRENT_TIMESTAMP},
  {name: "Wedding DJ", condition: "Good", minimum: 20, watchers: 2, endtime: CURRENT_TIMESTAMP},
  {name: "Door", condition: "Good", minimum: 20, watchers: 5, endtime: CURRENT_TIMESTAMP},
  {name: "Figurines", condition: "Good", minimum: 20, watchers: 5, endtime: CURRENT_TIMESTAMP},
  {name: "New Skates", condition: "Poor", minimum: 10, watchers: 5, endtime: CURRENT_TIMESTAMP},
  {name: "Black Suit", condition: "Poor", minimum: 20, watchers: 5, endtime: CURRENT_TIMESTAMP},
  {name: "Boots", condition: "Poor", minimum: 30, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "Canteen", condition: "Poor", minimum: 30, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "LOTR DVD Set", condition: "Poor", minimum: 30, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "A Real Product", condition: "Poor", minimum: 30, watchers: 3, endtime: CURRENT_TIMESTAMP},
  {name: "PS4", condition: "Poor", minimum: 30, watchers: 4, endtime: CURRENT_TIMESTAMP},
  {name: "DualShock Controller", condition: "Poor", minimum: 30, watchers: 4, endtime: CURRENT_TIMESTAMP},
  {name: "Video Games", condition: "Poor", minimum: 30, watchers: 4, endtime: CURRENT_TIMESTAMP},
  {name: "YouTube Account", condition: "Poor", minimum: 30, watchers: 4, endtime: CURRENT_TIMESTAMP},
  {name: "One Rib", condition: "Poor", minimum: 50, watchers: 5, endtime: CURRENT_TIMESTAMP},
  {name: "iPhone Case", condition: "Poor", minimum: 10, watchers: 5, endtime: CURRENT_TIMESTAMP},
  {name: "Trash", condition: "Poor", minimum: 15, watchers: 5, endtime: CURRENT_TIMESTAMP},
  {name: "Trash Can", condition: "Poor", minimum: 16, watchers: 5, endtime: CURRENT_TIMESTAMP}
];

const bidSeeds = [
  {productId: 1, amount: 140},
  {productId: 2, amount: 140},
  {productId: 3, amount: 140},
  {productId: 4, amount: 140},
  {productId: 5, amount: 140},
  {productId: 6, amount: 140},
  {productId: 7, amount: 140},
  {productId: 8, amount: 140},
  {productId: 9, amount: 140},
  {productId: 10, amount: 310},
  {productId: 11, amount: 310},
  {productId: 12, amount: 310},
  {productId: 13, amount: 310},
  {productId: 14, amount: 310},
  {productId: 15, amount: 310},
  {productId: 16, amount: 310},
  {productId: 17, amount: 310},
  {productId: 18, amount: 310},
  {productId: 19, amount: 310},
  {productId: 20, amount: 310},
  {productId: 21, amount: 160},
  {productId: 22, amount: 160},
  {productId: 23, amount: 160},
  {productId: 24, amount: 160},
  {productId: 25, amount: 160},
  {productId: 26, amount: 160},
  {productId: 27, amount: 160},
  {productId: 28, amount: 160},
  {productId: 29, amount: 160},
  {productId: 30, amount: 160},
  {productId: 31, amount: 160},
  {productId: 32, amount: 130},
  {productId: 33, amount: 130},
  {productId: 34, amount: 130},
  {productId: 35, amount: 130},
  {productId: 36, amount: 130},
  {productId: 37, amount: 130},
  {productId: 38, amount: 130},
  {productId: 39, amount: 130},
  {productId: 40, amount: 130},
  {productId: 41, amount: 130},
  {productId: 42, amount: 130},
  {productId: 43, amount: 800},
  {productId: 44, amount: 800},
  {productId: 45, amount: 800},
  {productId: 46, amount: 800},
  {productId: 47, amount: 800},
  {productId: 48, amount: 800},
  {productId: 49, amount: 800},
  {productId: 50, amount: 800},
  {productId: 51, amount: 800},
  {productId: 52, amount: 800},
  {productId: 53, amount: 800},
  {productId: 54, amount: 320},
  {productId: 55, amount: 320},
  {productId: 56, amount: 320},
  {productId: 57, amount: 320},
  {productId: 58, amount: 320},
  {productId: 59, amount: 320},
  {productId: 60, amount: 320},
  {productId: 61, amount: 320},
  {productId: 62, amount: 320},
  {productId: 63, amount: 320},
  {productId: 64, amount: 320},
  {productId: 65, amount: 812},
  {productId: 66, amount: 812},
  {productId: 67, amount: 812},
  {productId: 68, amount: 812},
  {productId: 69, amount: 812},
  {productId: 70, amount: 812},
  {productId: 71, amount: 812},
  {productId: 72, amount: 812},
  {productId: 73, amount: 812},
  {productId: 74, amount: 812},
  {productId: 75, amount: 812},
  {productId: 76, amount: 210},
  {productId: 77, amount: 210},
  {productId: 78, amount: 210},
  {productId: 79, amount: 210},
  {productId: 80, amount: 210},
  {productId: 81, amount: 210},
  {productId: 82, amount: 210},
  {productId: 83, amount: 210},
  {productId: 84, amount: 210},
  {productId: 85, amount: 210},
  {productId: 86, amount: 210},
  {productId: 87, amount: 123},
  {productId: 88, amount: 123},
  {productId: 89, amount: 123},
  {productId: 90, amount: 123},
  {productId: 91, amount: 123},
  {productId: 92, amount: 123},
  {productId: 93, amount: 123},
  {productId: 94, amount: 123},
  {productId: 95, amount: 123},
  {productId: 96, amount: 123},
  {productId: 97, amount: 123},
  {productId: 98, amount: 123},
  {productId: 99, amount: 345},
  {productId: 100, amount: 123}
];

const initialize = {
  product: (productSeeds) => {
    Product.bulkCreate(productSeeds);
  },

  bid: (bidSeeds) => {
    Product.bulkCreate(bidSeeds);
  }
}

module.exports = {
  initialize: initialize
};